/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2018-03-11 10:31:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.templates.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class navbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/KhoaLuan/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/clbtinhoc/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1487679517738L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-4.2.1.RELEASE.jar", Long.valueOf(1488893197413L));
    _jspx_dependants.put("jar:file:/D:/KhoaLuan/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/clbtinhoc/WEB-INF/lib/spring-security-taglibs-4.2.1.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1482315044000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-static-top\" role=\"navigation\" style=\"margin-bottom: 0\">\r\n");
      out.write("  <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("          <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("          <span class=\"icon-bar\"></span>\r\n");
      out.write("          <span class=\"icon-bar\"></span>\r\n");
      out.write("          <span class=\"icon-bar\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin\">Câu lạc bộ tin học</a>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <ul class=\"nav navbar-top-links navbar-right\">\r\n");
      out.write("      <li class=\"dropdown\">\r\n");
      out.write("          <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("              <i class=\"fa fa-envelope fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu dropdown-messages\">\r\n");
      out.write("              <li>\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                      <div>\r\n");
      out.write("                          <strong>John Smith</strong>\r\n");
      out.write("                          <span class=\"pull-right text-muted\">\r\n");
      out.write("                              <em>Yesterday</em>\r\n");
      out.write("                          </span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"divider\"></li>\r\n");
      out.write("              <li>\r\n");
      out.write("                  <a class=\"text-center\" href=\"#\">\r\n");
      out.write("                      <strong>Read All Messages</strong>\r\n");
      out.write("                      <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"dropdown\">\r\n");
      out.write("          <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("              <i class=\"fa fa-tasks fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu dropdown-tasks\">\r\n");
      out.write("              <li>\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                      <div>\r\n");
      out.write("                          <p>\r\n");
      out.write("                              <strong>Task 1</strong>\r\n");
      out.write("                              <span class=\"pull-right text-muted\">40% Complete</span>\r\n");
      out.write("                          </p>\r\n");
      out.write("                          <div class=\"progress progress-striped active\">\r\n");
      out.write("                              <div class=\"progress-bar progress-bar-success\" role=\"progressbar\" aria-valuenow=\"40\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 40%\">\r\n");
      out.write("                                  <span class=\"sr-only\">40% Complete (success)</span>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"divider\"></li>\r\n");
      out.write("              <li>\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                      <div>\r\n");
      out.write("                          <p>\r\n");
      out.write("                              <strong>Task 2</strong>\r\n");
      out.write("                              <span class=\"pull-right text-muted\">20% Complete</span>\r\n");
      out.write("                          </p>\r\n");
      out.write("                          <div class=\"progress progress-striped active\">\r\n");
      out.write("                              <div class=\"progress-bar progress-bar-info\" role=\"progressbar\" aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 20%\">\r\n");
      out.write("                                  <span class=\"sr-only\">20% Complete</span>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                  <a class=\"text-center\" href=\"#\">\r\n");
      out.write("                      <strong>See All Tasks</strong>\r\n");
      out.write("                      <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"dropdown\">\r\n");
      out.write("          <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("              <i class=\"fa fa-bell fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu dropdown-alerts\">\r\n");
      out.write("              <li>\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                      <div>\r\n");
      out.write("                          <i class=\"fa fa-comment fa-fw\"></i> New Comment\r\n");
      out.write("                          <span class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"divider\"></li>\r\n");
      out.write("              <li>\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                      <div>\r\n");
      out.write("                          <i class=\"fa fa-twitter fa-fw\"></i> 3 New Followers\r\n");
      out.write("                          <span class=\"pull-right text-muted small\">12 minutes ago</span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"divider\"></li>\r\n");
      out.write("              <li>\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                      <div>\r\n");
      out.write("                          <i class=\"fa fa-envelope fa-fw\"></i> Message Sent\r\n");
      out.write("                          <span class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"divider\"></li>\r\n");
      out.write("              <li>\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                      <div>\r\n");
      out.write("                          <i class=\"fa fa-tasks fa-fw\"></i> New Task\r\n");
      out.write("                          <span class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"divider\"></li>\r\n");
      out.write("              <li>\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                      <div>\r\n");
      out.write("                          <i class=\"fa fa-upload fa-fw\"></i> Server Rebooted\r\n");
      out.write("                          <span class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"divider\"></li>\r\n");
      out.write("              <li>\r\n");
      out.write("                  <a class=\"text-center\" href=\"#\">\r\n");
      out.write("                      <strong>See All Alerts</strong>\r\n");
      out.write("                      <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"dropdown\">\r\n");
      out.write("          <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("              <i class=\"fa fa-user fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu dropdown-user\">\r\n");
      out.write("              <li><a href=\"#\"><i class=\"fa fa-user fa-fw\"></i> User Profile</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li><a href=\"#\"><i class=\"fa fa-gear fa-fw\"></i> Settings</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"divider\"></li>\r\n");
      out.write("              <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\"><i class=\"fa fa-sign-out fa-fw\"></i> Logout</a>\r\n");
      out.write("              </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"navbar-default sidebar\" role=\"navigation\">\r\n");
      out.write("      <div class=\"sidebar-nav navbar-collapse\">\r\n");
      out.write("          <ul class=\"nav\" id=\"side-menu\">\r\n");
      out.write("              <li>\r\n");
      out.write("                  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin\"><i class=\"fa fa-dashboard fa-fw\"></i> Trang chủ</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              ");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("          </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /.sidebar-collapse -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.navbar-static-side -->\r\n");
      out.write("</nav>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/templates/admin/navbar.jsp(166,14) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("hasAnyRole('ROLE_ADMIN','ROLE_VICE')");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("\t              <li>\r\n");
        out.write("\t                  <a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/admin/users\"><i class=\"fa fa-dashboard fa-fw\"></i> Quản lý thành viên</a>\r\n");
        out.write("\t              </li>\r\n");
        out.write("              ");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }
}
